export const GET_STUDENTS = "GET_STUDENTS";
export const RESET_ASSIGNMENT_STATE = "RESET_ASSIGNMENT_STATE";

// Assignment Form State Actions
export const CHANGE_STEP_TO_GRADES = "CHANGE_STEP_TO_GRADES";
export const CHANGE_STEP_TO_COMPLETE = "CHANGE_STEP_TO_COMPLETE";
export const RESET_FORM_STATE = "RESET_FORM_STATE";
export const SET_ASSIGNMENT = "SET_ASSIGNMENT";

//Nav State actions
export const SET_NAV_HOME = "SET_NAV_HOME";
export const SET_NAV_NEW_STUDENT = "SET_NAV_NEW_STUDENT";
export const SET_NAV_NEW_TEACHER = "SET_NAV_NEW_TEACHER";
export const SET_NAV_NEW_ASSIGNMENT = "SET_NAV_NEW_ASSIGNMENT";
export const DEACTIVATE_NAV = "DEACTIVATE_NAV";
export const ACTIVATE_NAV = "ACTIVATE_NAV";
